project:
  type: website
  output-dir: docs

website:
  title: "Eli Della Bitta - Data Science Portfolio"
  navbar:
    right: 
      - text: "About Me"
        href: index.html
      - text: "Data Viz"
        menu: 
          - text: "Netflix Analysis"
            href: netflix-analysis.html
          - text: "Coffee Ratings"
            href: coffee-analysis.html
          - text: "Text Analysis"
            href: text-analysis.html
            text: "Simulation Study"
            href: simulation-study.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
